GET http://localhost:5000/api/rooms 

###

POST http://localhost:5000/api/rooms HTTP/1.1
content-type: application/json

{
    "name": "Trio",
    "maxPersons": 3,
    "promo": false
}

### 

PATCH http://localhost:5000/api/rooms/623ca5312d48cc352066227e HTTP/1.1
content-type: application/json

{
    "name": "Basique duo",
    "promo": true
}

### 

GET http://localhost:5000/api/rooms/623ca20f7fbab650fc868e77